### PR TITLE
Small change to domain RE

### LINKED ISSUE #66: domain('foo.bar/baz') validates as 'True'
```
# bin/pip3 show validators
Name: validators
Version: 0.12.0
...
# bin/python3
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from validators import domain
>>> domain('foo.bar.baz')
True
>>> domain('foo/bar.baz')
ValidationFailure(func=domain, args={'value': 'foo/bar.baz'})
>>> domain('foo.bar/baz')
True
>>> domain('foo.bar/')
ValidationFailure(func=domain, args={'value': 'foo.bar/'})
>>>
```

### LINKED ISSUE #71: Domain Validator - International Domains
I think that the domain validator does not word for all cases of international domains, eg. thepiratebay.xn--fiqs8s is a working domain but the validator says it is invalid.

I located a fix in the code I believe should fix the issue - in the regex pattern:

pattern = re.compile(
    r'^(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|'
    r'([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|'
    r'([a-zA-Z0-9][-_.a-zA-Z0-9]{0,61}[a-zA-Z0-9]))\.'
    r'([a-zA-Z]{2,13}|[a-zA-Z0-9-]{2,30}.[a-zA-Z**0-9**]{2,3})$'
)

Cheers

### LINKED ISSUE #73: validators.domain('a......b.com') returns True
I guess this is an error.

### PR DESCRIPTION
**Pull request by Ni-Knight**
fixes #73 
fixes #71 
fixes #66

### CODE REVIEW

**Comment by Ni-Knight** [comment]
@kvesteri nvm 😄

**Comment by kvesteri** [comment]
Squash the commits, otherwise looks good.

**Comment by Ni-Knight** [comment]
@kvesteri How do I squash the commits on github =\
Couldn't find it.

**Comment by kvesteri** [comment]
Thanks for the PR! 🌮

**Pull request merged**
