### PR TITLE
build with pyp2rpm problem

### PR DESCRIPTION
**Pull request by BOPOHA**
fix build_requires

### CODE REVIEW

**Comment by BOPOHA** [comment]
@kvesteri up!

**Comment by kvesteri** [comment]
What is the build_requires used for? I couldn't find it in the setuptools documentation.

**Comment by BOPOHA** [comment]
there are a few difference between BuildRequires and Requires tag in rpm spec-file.
so it needs to add BuildRequires section to specs.

please look at the errors here 
https://copr.fedorainfracloud.org/coprs/vorona/python2/build/473003/

>    File "/builddir/build/BUILD/validators-0.11.0/validators/utils.py", line 6, in <module>
    from decorator import decorator
> ImportError: No module named 'decorator'

**Comment by kvesteri** [comment]
Thanks for the PR! :train:

**Comment by BOPOHA** [comment]
Please pull updates to PyPI: https://pypi.python.org/pypi/validators

**Comment by kvesteri** [comment]
Done! :+1:

**Comment by Alessandro-Barbieri** [comment]
Now this build_requires is causing me problems

**Pull request merged**
