### PR TITLE
Support IPv4-compatible + IPv4-mapped

### PR DESCRIPTION
**Pull request by vuolter**
Add support for IPv4-compatible address and IPv4-mapped address
Code cleanup and small speedup

### CODE REVIEW

**Comment by kvesteri** [comment]
Before merging this needs unit tests and docs.

**Comment by vuolter** [comment]
Sorry for the multiple commits... :s

**Comment by kvesteri** [comment]
Squash the commits and fix the flake8 code styling issues (see travis CI for details), otherwise this seems good.

**Comment by vuolter** [comment]
Done. You can squash the commits directly here on github when merging them, bye. 😄

**Pull request merged**
