### PR TITLE
Fix domain validation

### LINKED ISSUE #47: domain validator fails for äöü
if a domain contains german letters like ä, ö or ü, which would be valid, the validator fails.

### LINKED ISSUE #123: Domain validator now too permissive
Hello,

It seems any string composed of numbers separated by dots is now accepted by  the domain validator.

```
>>> validators.domain("123.123")
True

>>> validators.domain("123.123.123")
True

>>> validators.domain("123.123.123.123")
True
```

It didn't use to be the case (I know because it now causes some errors in my unit tests in the "naval" library)
I think it was good that these strings weren't accepted as domains. I don't think these are valid domains.

### PR DESCRIPTION
**Pull request by jmeridth**
- Updated regex to not allow numeric only TLDs (examples in tests)
- Allow for idna encoded domains and test for them (examples in tests)

Fixes #47
Fixes #123

### CODE REVIEW

**Comment by jmeridth** [comment]
Failing specs in different python versions.  Fixing.

**Comment by jmeridth** [comment]
@kvesteri thank you for the merge. May I inquire when the next pypi release will be? Thank you for creating this project.

**Comment by kvesteri** [comment]
Released version 0.14.1 with this included

**Comment by jmeridth** [comment]
@kvesteri thank you very much.  Cheers 🍻

**Pull request merged**
