### PR TITLE
Adds ES doi / nie / cif / nif

### PR DESCRIPTION
**Pull request by kingbuzzman**
~- Adds Locale() to abstract away the region.~
- Adds Spanish nie / nif / cif / doi validation

### CODE REVIEW

**Comment by kingbuzzman** [comment]
@kvesteri how do i compile the docs so i can test them out?

**Comment by kvesteri** [comment]
Thanks for the PR. What is the benefit of the Locale class?

I would rather use syntax of something like:

```python
import validators

validators.fi.business_id('0112038-9')

validators.es.cif('B25162520')
```

rather than having to always initialize a new Locale object. Another problem with the Locale object is that it is easily confused with Bable Locale object.

**Comment by kingbuzzman** [comment]
@kvesteri I mean the whole idea is to abstract away the whole i18n and make it seamless. The way i envision this is: (this may be a horrible example, but just attempt to get by point across)

_validators/temperature.py_
```
@validator
def livable_temperature(temp):
     """Assuming celcius"""
     return 50 > temp > -30
```

_validators/i18n/us/temperature.py_
```
@validator
def us_livable_temperature(temp):
     """When will the US get with the times?!"""
     return 122 > temp > -22
```

_in your code_
```
from validators import Locale

def is_valid_temp(temp):
    validators = Locale()
    return validators.livable_temperature(temp)

is_valid_temp(75)  # if in the US  # this is `True`
is_valid_temp(25)  # if ANYWHERE else in the world  # this is `True`
```

Put it simply, the idea is to be able to not need to know the locale in order to use it. Its seamless to the user, the user simply just uses the validator, we do the heavy lifting underneath the covers. 

If you're concerned with having the name `Locale` as it can be confused with Bable `Locale`. The user  can simply do `from validators import Locale as ValidatorLocale` or something around those lines. ... Does that make any sense? I can try again with another horrible example :P

**Comment by kvesteri** [comment]
I'm just not convinced by either this branch or the example you gave that the having a Locale class would be the way to go. The whole point of this library is to have a collection of immutable functions. I'd prefer not have anything containing a state.

**Comment by kingbuzzman** [comment]
@kvesteri Hey, this is your repo. You're the benevolent dictator here. I will remove the Locale and leave the rest of the validation code.

**Comment by kingbuzzman** [comment]
@kvesteri friendly ping.

**Comment by kingbuzzman** [comment]
@kvesteri can you let me know when you publish this please? I have a PR over at https://github.com/joke2k/faker/pull/959 that needs a version. Thanks.

**Comment by kvesteri** [comment]
Already released (0.13.0)

**Comment by kingbuzzman** [comment]
@kvesteri ps. https://validators.readthedocs.io/en/latest/ doc looks old.

**Pull request merged**
